// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjUzhaTbFEYSH-hBBdsto_GY39a16I0sQ',
    appId: '1:78533009743:web:8d4b54c5a13048c8ece53a',
    messagingSenderId: '78533009743',
    projectId: 'studi-kasus-to-do-list',
    authDomain: 'studi-kasus-to-do-list.firebaseapp.com',
    storageBucket: 'studi-kasus-to-do-list.appspot.com',
    measurementId: 'G-79WKXZCSYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9pyhqci2pC6qwJ_3mo6j9cRt7iPzc6rs',
    appId: '1:78533009743:android:88aa8087a87f7d46ece53a',
    messagingSenderId: '78533009743',
    projectId: 'studi-kasus-to-do-list',
    storageBucket: 'studi-kasus-to-do-list.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaI-Y-A39RxgyGmK6BGyj0CC9X5tr69bU',
    appId: '1:78533009743:ios:3e0c95d5e3c49988ece53a',
    messagingSenderId: '78533009743',
    projectId: 'studi-kasus-to-do-list',
    storageBucket: 'studi-kasus-to-do-list.appspot.com',
    iosBundleId: 'com.example.baseTodolist',
  );
}
